### ISSUE TITLE
Implement `PartialEq` etc.

### ISSUE THREAD

**Issue by dpc** [Kimundi/owning-ref-rs#6]
I'm not sure if it's a good idea, but it seems to me that `OwningRef` could implement `PartialEq`, `Eq` etc. that just do it on `T` itself.

**Comment by milancio42** [comment]
IMHO it's a good idea. I need to put `OwningRef` into `HashMap`, but currently I cannot, since `Hash` is a foreign trait and `OwningRef` is a foreign type. I would need to wrap it into my type, but that is just not ergonomic, since I would need to re-implement all the necessary methods from `OwningRef`.
The implementation should be trivial - I can prepare the PR (`Eq`, `PartialEq`, `Ord`, `PartialOrd` and `Hash`) if the owner agrees.

**Comment by waywardmonkeys** [comment]
This was resolved when #7 was landed, right?

**Comment by meh** [comment]
Yes, this can be closed.
